language: python

python:
  - "2.7"
  - "pypy"

services:
  - riak
  - redis-server

install:
  - sudo apt-get update -qq
  - sudo apt-get install protobuf-compiler
  - pip install -r requirements.txt --use-mirrors

before_script:
  - search-cmd install users
  - search-cmd set-schema users ./install/rs-schema/users.config

script: nosetests

notifications:
  email: false


# vim:set ai et ts=2 sw=2 sts=2 fenc=utf-8:
